# Generated by Django 5.2.4 on 2025-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_theme_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
