# Generated by Django 5.2.4 on 2025-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_journalentry_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='writing_time',
            field=models.IntegerField(default=0, help_text='Time spent writing in seconds'),
        ),
    ]
