# Generated by Django 5.2.4 on 2025-12-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_emotion_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', help_text='Control who can view this entry', max_length=10),
        ),
    ]
