# Generated by Django 5.2.4 on 2025-12-16 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_tag_journalentry_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='JournalEntryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('prompt', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, help_text="Human-readable description of what changed (e.g., 'Title and answer updated')", max_length=255)),
                ('edit_source', models.CharField(choices=[('initial', 'Initial Creation'), ('edit', 'Manual Edit'), ('restore', 'Restored from Version')], default='initial', max_length=20)),
                ('restored_from_version', models.IntegerField(blank=True, help_text="If edit_source='restore', the version number that was restored", null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='authentication.journalentry')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.theme')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['entry', '-version_number'], name='authenticat_entry_i_f7e1dd_idx'), models.Index(fields=['created_at'], name='authenticat_created_594733_idx')],
                'unique_together': {('entry', 'version_number')},
            },
        ),
    ]
