# Generated by Django 5.2.4 on 2025-12-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_journalentry_last_modified_at_journalentryversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('one_time', 'One-time'), ('recurring', 'Recurring')], default='one_time', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('run_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='authentication.journalentry')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'next_run_at'], name='authenticat_is_acti_5d7eb9_idx')],
            },
        ),
    ]
