# Generated by Django 5.2.4 on 2025-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_quick_add_fab',
            field=models.BooleanField(default=True, help_text='Show the Quick Add FAB button on the home page'),
        ),
    ]
