# Generated by Django 5.2.4 on 2025-12-22 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customuser_show_quick_add_fab'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text="Type of event (e.g., 'quick_add_fab_clicked')", max_length=100)),
                ('event_data', models.JSONField(default=dict, help_text='Additional event data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type', '-timestamp'], name='authenticat_user_id_203793_idx'), models.Index(fields=['event_type', '-timestamp'], name='authenticat_event_t_331ed8_idx')],
            },
        ),
    ]
