# Generated by Django 5.2.4 on 2025-12-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Changes the default value of show_quick_add_fab from True to False.
    
    NOTE: This migration only affects the default value for NEW users.
    Existing users will retain their current preference setting.
    
    NULL HANDLING: The field definition includes default=False, which means:
    - New users created after this migration will have show_quick_add_fab=False
    - Existing users with explicit True/False values are unaffected
    - NULL values should not exist because the field was defined with a default
      in the original migration, but if any exist, Django will use False on save
    """

    dependencies = [
        ('authentication', '0011_analyticsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='show_quick_add_fab',
            field=models.BooleanField(default=False, help_text='Show the Quick Add FAB button on the home page'),
        ),
    ]
